name: Linux Build

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install Dependencies
      run : |
        sudo bash -c 'deb http://us.archive.ubuntu.com/ubuntu focal main universe" >> /etc/apt/sources.list.d/unstable.list'
        sudo apt-get -y update
        sudo apt-get -y remove clang-6.0 libclang-common-6.0-dev libclang1-6.0 libllvm6.0
        sudo apt-get -y install -t focal clang clang-format clang-tidy libsdl2-dev libfftw3-dev librtaudio-dev

    - name: Build GCC
      run: |
        rm -rf build/
        mkdir build
        cd build
        CC=gcc CXX=g++ cmake -DCMAKE_BUILD_TYPE=Release ..
        make clean
        make -j
        cd ..

    - name: Build Clang
      run: |
        rm -rf build/
        mkdir build
        cd build
        CC=clang CXX=clang++ cmake -DCMAKE_BUILD_TYPE=Release ..
        make clean
        make -j
        cd ..